### ISSUE TITLE
 [Query] Bidali In-AppCTA not shown at first position in home screen after restoring account with verified number

### ISSUE THREAD

**Issue by ValoraQA** [valora-inc/wallet#1011] opened 2021-08-19 11:19 UTC
**Frequency:** 100%
**Repro on build version:** Testflight build V1.18.0 &  Android Internal build V1.18.0
**Repro on devices:** Redmi Note 8 (9.0), Vivo v11 pro (10), iPhone 6+ (12.0), Samsung Galaxy J5 Prime (8.0), iPhone XR (14.6)
**Testing Account:**   (408) 657 3238 / [Account Key](https://docs.google.com/spreadsheets/d/1gXY1I4PBkT9f1uB3zxWgUUJJ1zjVeJcqcWLjiIls1f0/edit#gid=0&range=B74)
**Pre-condition:** Make sure that user should have account key with verified phone number & no any request (Sent/ Received / Reclaim Amount) in CTA
**Repro Steps:**
1. Launch the application & log in with the test account 
2. Go to Home screen
3. Observe first In-App CTA 
**Current Behavior:**   “Fund your account & start earning 5% on your savings! You can start with 1cUSD ! " In-App CTA first after restoring account” In-App CTA displayed as 1st position
**Expected Behavior:**  “Now Available: Buy Gift Cards and Mobile Top Up through Bidali” In-App CTA should be displayed as 1st CTA position
**Investigation:** Also We have observed that user able to see “Valora allows you to buy and sell CELO” In-App CTA.
**Attachment:** [In-AppCTASequenceForBackedUpAccount.mp4](https://drive.google.com/file/d/1m6TN6QvYZZhP4zlvfGGYYAneepjhYY8u/view?usp=sharing)

**Comment by ValoraQA** [comment] 2021-08-19 11:20
https://valora.testquality.com defect [D98](https://valora.testquality.com/project/12128/result/2469338/defect/8148).

**Comment by MuckT** [comment] 2021-08-19 14:46
@gnardini it looks like unfunded accounts have the 'fund your account CTA' prior to the 'Bidali CTA', is this the expected behavior on Alfajores?

**Comment by gnardini** [comment] 2021-08-19 16:48
Yes, the expected behavior was in Alfajores, should have clarified that.

For mainnet the order will be chosen by the marketing team and might change at any time.

**Comment by ValoraQA** [comment] 2021-08-20 13:44
Hey @MuckT I have verified this issue using Alfajores build V1.18.0(72) & observed following observation:
**Observation:**

- [ ] User able to see "You're eligible to earn rewards on your cUSD balance!" In-App CTA at first position after creating new account 
- [ ] Also user able to see "You're eligible to earn rewards on your cUSD balance!" In-App CTA at first position after restoring any verified account. [Attachment](https://drive.google.com/file/d/1GDM8iz-yOROBx2i2hocrCj0HDbXo3Hml/view?usp=sharing)

**Investiagtion:** We have not observed Bidali In-app CTA for both scenarios 
**Verified On Devices:** iPhone XR (14.6)
Thanks..!!

**Comment by MuckT** [comment] 2021-08-20 19:21
@ValoraQA closing this issue as the expected results were observed. Please reach out for any additional clarification.

**Closed by MuckT** 2021-08-20 19:21 UTC
Labels: bug, Priority: P3, Component: Feed & Notifications
