### ISSUE TITLE
Add page with streamlined view of transaction details when connecting / signing with dapps

### ISSUE THREAD

**Issue by jeanregisser** [valora-inc/wallet#2102] opened 2022-03-08 14:26 UTC
These designs have been reviewed & are ready for pre-refinement!

https://www.figma.com/file/zdK8XvxNXvTjxnM5V33pHw/Dapps-Page?node-id=2130%3A47756

![image.png](https://images.zenhubusercontent.com/60aebf1846d8443435496013/d80b4b23-c56b-4eec-9522-57c1d1d95185)

ENG
- if connecting from in-app dapp, display the dapp logo
- if connecting from external dapp, display no logos

**Comment by kathaypacific** [comment] 2022-05-10 08:58
Closing as a duplicate of #2342

**Closed by kathaypacific** 2022-05-10 08:58 UTC
Labels: Squad: Retention
