### ISSUE TITLE
WalletConnect opens Valora website homepage in the browser instead of the app

### ISSUE THREAD

**Issue by aleksey-nov** [valora-inc/wallet#1418] opened 2021-11-11 14:06 UTC
ios, Valora 1.21.0
When connecting wallet using WalletConnect to sushi.com on a mobile device, Valora's website homepage (`https://valoraapp.com/wc`) is being opened in the browser. Expected behavior: user will see the transaction signing screen in Valora instead.

To do:
- Evaluate how many users are impacted;
- Add acceptance criteria before the refinement meeting.

ENG:
* This doesn't happen 100% of the time (unsure what triggers it)
* There's a configuration file iOS downloads at Valora install time (and possibly other times) that configures `https` URL handlers (_i.e._, `https://valoraapp.com/wc` should be handled by Valora)
* It might be hard to prevent this (but possible to workaround / mitigate)
* If you need access to GA post in #data channel requesting access

AC:
* See how many users are impacted (_i.e._, via GA for https://valorapp.com/wc)
* Share results in the #retention-squad channel
* Propose a priority for investigating a fix based on users impacted

**Comment by ValoraQA** [comment] 2021-11-12 12:37
Hey, @aleksey-nov We have verified this issue using Playstore build V1.22.0 & App store build V1.22.0 & observed the following observations:
**Valora app installed:** 
- It is observed that, the issue is not repro as the user is able to redirect to the Valora app & not in the browser after tapping on Connect button on the sushi.com page. [Attachment](https://drive.google.com/file/d/1OUsRPICofCnKJR9AumRClYovbwvmwDyc/view?usp=sharing)

**Valora app not installed:**
- It is observed that the user redirects to valoraapp.com after tapping on Connect button on the sushi page. [Attachment](https://drive.google.com/file/d/1fspNx8ALtykgqjhDTV9un816T6uV9L1W/view?usp=sharing)

- [x] Also, it seems expected to us as it redirects the user to download an app first to connect the wallet with Valora.

**Verified On Devices:**  Redmi Note 8(9.0), Redmi Note 8 (10.0), iPhone 12 (15.0), iPhone 6+ (12.4.5)

**Comment by MuckT** [comment] 2021-12-21 16:59
Was this fixed by https://github.com/valora-inc/valora-website/pull/222?

**Comment by jeanregisser** [comment] 2022-01-20 15:09
Here's the data: in the last 30 days about 350 unique users landed on `https://valoraapp.com/?uri=wc:XXX` urls trying to connect to Valora via WalletConnect. 
It's impossible to know if they actually had Valora installed and bumped into this random iOS issue with universal links.

Source: GA, see https://valora-app.slack.com/archives/C02DY3RK79T/p1642604619032400?thread_ts=1642603482.030300&cid=C02DY3RK79T

**Closed** 2022-01-25 17:08 UTC
Labels: bug, Priority: P2, Squad: Retention, Component: WalletConnect
