### ISSUE TITLE
 [Specific device] Phone number gets cut on search bar when user enter any phone number on search bar in Send page 

### ISSUE THREAD

**Issue by Lss-Ankit** [valora-inc/wallet#593] opened 2021-02-08 13:09 UTC
**Frequency:** 100%
**Repro on build version:** Android Internal Build V1.9.2(1004294334)
**Does not repro version** Test Flight Build V1.9.2(44)
**Repro on devices:** Samsung A20S (10)
**Does not repro devices** iPhone 8(14.2), iPhone 12 (14.2), Samsung M30(10)
**Testing Account:** 272 381 9637 / [Backup Key](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit#gid=0&range=B22)
 **Repro Steps:**
1. Launch the application and login with a test account.
2. Tap on send button
3. Enter any phone number
4. Observe  
**Current Behavior:**  Phone number gets cut on search bar.
**Expected Behavior:**  User should able to see the full phone number without any cut.
**Impact:** User not able to see the full phone number .
**Attachment:**  [PhonenumberCuts](https://drive.google.com/file/d/1oeDmnNlf2PF897inFt7EIuWC2oS1N7_i/view?usp=sharing)

**Comment by ValoraQA** [comment] 2022-03-23 10:55
Hey @MuckT, We have verified the above issue on Latest android internal build V1.28.1 & observed that the issue is fixed now.
Phone number does not get cut when user enter any phone number on search bar on send page.
Hence We are closing this issue.

**Devices:** Google Pixel XL (10.0), Samsung Galaxy M40(10.0)
**Attachment:** [Phone number issue.jpg](https://drive.google.com/file/d/168U6ZsNFEmCjdTTmY8PJ2w60inyN9fOd/view?usp=sharing)
Thanks..!!

**Closed by ValoraQA** 2022-03-23 10:55 UTC
Labels: Component: Send/Request, Priority: P4, android, wallet, qa-report
